name: job_postings
version: "1.0.0"
config-version: 2

profile: job_postings

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  job_postings:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
