name: 'analytics'
profile: 'analytics'

models:
  analytics:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
    utilities:
      +materialized: table
      +schema: gold

seeds:
  analytics:
    +schema: silver
